version: "3.7"

services:

    php:
        container_name: stocky-php
        build: docker/php
        environment:
            - DEBUG=1
        working_dir: /var/www/stocky
        volumes:
            - ./:/var/www/stocky
        extra_hosts:
            - "host.docker.internal:host-gateway"

    nginx:
        container_name: stocky-nginx
        build: docker/nginx
        links:
            - php
        ports:
            - "8003:80"
        working_dir: /var/www/stocky
        volumes:
            - ./:/var/www/stocky
